sudo: require
dist: xenial
cache: apt
env:
  - OUTPUT_DIR=public

before_install:
  # install texlive
  - sudo apt-get -qq update
  - sudo apt-get install -y texlive-base
  - sudo apt-get install -y texlive-latex-base
  - sudo apt-get install -y texlive-latex-extra
  - sudo apt-get install -y texlive-fonts-recommended
  - sudo apt-get install -y texlive-fonts-extra
  - sudo apt-get install -y texlive-full
  # set deploy_key
  - openssl aes-256-cbc -K $encrypted_a534f1c817d9_key -iv $encrypted_a534f1c817d9_iv -in deploy_key.enc -out deploy_key -d
  - chmod 600 deploy_key
  - eval `ssh-agent -s`
  - ssh-add deploy_key
  - git config --global user.name "Travis-CI"
  - git config --global user.email "travis-ci@example.com"
  # modify timezone
  - echo 'Asia/Tokyo' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata

script:
  - bash build.sh
  - '[ "$TRAVIS_BRANCH" == master ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && bash ./deploy.sh'
